finally: rewrite the shitty installer (#78)
* wip

* wip

* security ehehehehe

* makefile skill issues and some inst additions

* moreeee

* docstrings

* remove binutils from preinstalled packages

* full chroot at the end

* REMOVE SHITTY SHIT

* a lot of stuff

* A LOT OF SHIT

* create /root dir

* wip

* whoops

* h

* finish stuff

* fix whoopsie

* fix typo

* remove no longer needed

* fixes

* cool stuff

* more cool shit

* fix copy paste issue

* git issues

* improvements

* safety for ask_blkdev

* h

diff --git a/rootfs/filesystem/etc/runit/1 b/rootfs/filesystem/etc/runit/1
--- a/rootfs/filesystem/etc/runit/1
+++ b/rootfs/filesystem/etc/runit/1
@@ -26,6 +26,9 @@ if [ "$mount_failed" -eq 1 ]; then
   exec /bin/sh
 fi
 
+echo -e "\e[94m::\e[0m Remounting / read-write"
+mount -o remount,rw / || ( echo -e "  \e[91m*\e[0m Critical error: remounting / read-write failed" ; echo "  * Starting a rescue shell" ; exec /bin/sh )
+
 echo -e "\e[94m::\e[0m Setting font"
 setfont -C /dev/console /usr/share/consolefonts/ter-m16n.psf.gz || ( echo -e "  \e[91m*\e[0m Failed to set font." ; sleep 1 )
 
